### ISSUE TITLE
cf::makl_optional fix

### ISSUE THREAD

**Issue by babongo** [koanlogic/makl#1]
Let makl_optional search for static libraries (instead of dynamic/shared) when checking for library dependency fulfillment.

**Comment by stewy** [comment]
makl_optional already searches for both static and dynamic libraries (in that order); if there are issues with a specific usage we need to look into them specifically - please provide more detail, thanks

**Comment by babongo** [comment]
Hi stewy :), a couple of things:
1) I'd like:
    makl_optional 1 lib z
to set LIBZ_LDADD.  At present only LIBZ_{CFLAGS,LDFLAGS} are created (when libz is found).
2) I'd like the search path logics to be more transparent -- and overrideable -- , e.g.:
    makl_optional 1 lib z "/my/main/path /my/secondary/path"
to search for libz into /my/main/path and into /my/secondary/path as a fallback.
3) It'd be nice if I could explicitly require shared linking, static or both.
